version: "3"

services:
  postgres:
    container_name: postgres-rust
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin-rust
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    env_file:
      - docker.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: